whl-u: Add ACPI methods for charging thresholds
system76/coreboot pull request #15
Opened 2020-06-04 20:46 UTC by crawfxrd

2020-07-09 14:52 UTC, lapolinar commented
@lapolinar

2020-09-15 14:52 UTC, jackpot51 requested changes

2020-09-15 14:52 UTC, jackpot51 commented on src/ec/system76/ec/acpi/battery_thresholds.asl
> +Method (BCTG, 2, NotSerialized)
To follow the paradigm of the other ACPI methods, I would recommend having these functions be GBCT and SBCT. And I would also recommend a NBCT function that can be used to get the canonical number of battery thresholds, so the ACPI driver can adapt to show any number.

2020-09-15 14:52 UTC, jackpot51 commented on src/ec/system76/ec/acpi/battery_thresholds.asl
> +Method (BCTG, 2, NotSerialized)
See the NTMP and NFAN functions for a reference

2020-09-15 21:42 UTC, crawfxrd commented on src/ec/system76/ec/acpi/battery_thresholds.asl
> +Method (BCTG, 2, NotSerialized)
I don't understand how `NBCT` would be used. Per [sysfs-class-power](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power) they should be exposed as `/sys/class/power_supply/<supply_name>/charge_control_{start,end}_threshold`, rather than a `<foo>_{input,label}` pair in hwmon.

2020-09-18 17:57 UTC, jackpot51 commented on src/ec/system76/ec/acpi/battery_thresholds.asl
> +Method (BCTG, 2, NotSerialized)
What is the indicator to the OS that a battery exists? Right now just looking at the GBCT function would make it appear that two batteries exist in all cases

2020-09-18 18:57 UTC, crawfxrd commented on src/ec/system76/ec/acpi/battery_thresholds.asl
> +Method (BCTG, 2, NotSerialized)
Looking at the ThinkPad implementation, they added functions to each battery and then exposed a higher level function that gets used by the kernel driver. So if a battery isn't present it would result in an error.

2020-09-21 16:14 UTC, jackpot51 approved these changes

2020-09-21 16:15 UTC, jackpot51 commented
It looks very clean to me now.

2020-09-21 16:43 UTC, jackpot51 commented
I checked and proprietary EC appears to not use these locations, which is good.

2020-09-22 20:08 UTC, jacobgkau approved these changes
Tested with https://github.com/pop-os/system76-acpi-dkms/pull/4.

2020-09-22 22:08 UTC, merged